### ISSUE TITLE
复现时报错模型加载失败

### ISSUE THREAD

**Issue by YMMF007** [decisionintelligence/DUET#2]
您好，我按照readme文件操作。我上传好了数据集，没有修改代码。
但复现时，报以下错误，能麻烦您看看问题出在哪吗
![image](https://github.com/user-attachments/assets/c4f1a6e0-8053-48cc-84c8-67e9604852fc)

**Comment by YMMF007** [comment]
还有请问一下python版本有要求吗，我用的3.10，但是cmake时好像有点问题，请问您用的是哪个版本

**Comment by qiu69** [comment]
Python为3.8



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月24日 23:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [decisionintelligence/DUET] 复现时报错模型加载失败 (Issue #2) |

还有请问一下python版本有要求吗，我用的3.10，但是cmake时好像有点问题，请问您用的是哪个版本

**Comment by qiu69** [comment]
@YMMF007 请问，问题解决了嘛？如果没有解决，方便的话请加我微信：qxf780310。

**Comment by gintmr** [comment]
您好，可以问一下是怎么解决的吗？我也遇到这个问题了

**Comment by qiu69** [comment]
@gintmr 好滴，谢谢您宝贵意见，请问您可以发起发起pull request吗。也方便您成为贡献者。建议您把python版本改为3.8试一下。

**Comment by gintmr** [comment]
> [@gintmr](https://github.com/gintmr) 好滴，谢谢您宝贵意见，请问您可以发起发起pull request吗。也方便您成为贡献者。建议您把python版本改为3.8试一下。

您好，不好意思我刚看见，我刚刚发起了pull request~🫡

**Comment by gintmr** [comment]
> [@gintmr](https://github.com/gintmr) 好滴，谢谢您宝贵意见，请问您可以发起发起pull request吗。也方便您成为贡献者。建议您把python版本改为3.8试一下。

我按照readme来配置的环境，python版本正好就是3.8

**Comment by qiu69** [comment]
@gintmr 方便加一下微信吗：qxf780310.方便沟通

**Comment by gintmr** [comment]
> [@gintmr](https://github.com/gintmr) 方便加一下微信吗：qxf780310.方便沟通

加您了
